### ISSUE TITLE
Do not duplicate the `get_the_time` tool

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/plugin-template#1]
Core already contains a `get_the_time` tool.
I suggest having a different example (`get_the_hour`, `say_hello` or something easy) so tools don't get duplicated in the installation

**Comment by zAlweNy26** [comment]
Do you manage to create a PR to fix that? Otherwise I can help you 🤪😂

**Comment by pieroit** [comment]
Yes I'll do it

**Comment by nicola-corbellini** [comment]
I changed the sample tool with a similar one that returns the day of the week in a string format

**Comment by pieroit** [comment]
@nicola-corbellini great <3

**Comment by AndreaGiaccherini** [comment]
I found that, in my case, the default timezone is GMT+2, using tzlocal would be automatically detect the timezone. I actually tested it but i don't know how to install a library in the container.

**Comment by AndreaGiaccherini** [comment]
Cheshire cat gets the wrong time because it gets the wrong timezone.

Do you have any clue why my timezone is "Etc/UTC" and not "Europe/Rome".

`from tzlocal import get_localzone`
`get_localzone()`

When run in the cheshire cat container yeild: zoneinfo.ZoneInfo(key='Etc/UTC'

Under my main python env the timezone is correct.

**Comment by nicola-corbellini** [comment]
That's because the Cat runs inside Docker and the default timezone is UTC (https://www.google.com/search?channel=fs&client=ubuntu-sn&q=docker+timezone)
